version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    versioning-strategy: "increase-if-necessary"
    rebase-strategy: "auto"
    reviewers:
      - gbouvignies
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      chemex-core:
        patterns:
          - "numpy*"
          - "scipy*"
          - "lmfit*"
      chemex-aux:
        patterns:
          - "matplotlib*"
          - "cachetools*"
          - "emcee*"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    rebase-strategy: "auto"
    reviewers:
      - gbouvignies
    groups:
      core:
        dependency-type: "production"
        patterns:
          - "*"
      dev:
        dependency-type: "development"
        patterns:
          - "dev"
      extras:
        patterns:
          - "docs"
          - "test"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - gbouvignies

  - package-ecosystem: "npm"
    directory: "/website/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - gbouvignies
    groups:
      # All Docusaurus-related packages together to avoid conflicts
      docusaurus:
        patterns:
          - "@docusaurus/*"
          - "@mdx-js/react"
          - "rehype-katex"
          - "remark-math"
      # React ecosystem separate from Docusaurus
      react:
        patterns:
          - "react"
          - "react-dom"
      # Other runtime dependencies
      runtime:
        dependency-type: "production"
        patterns:
          - "clsx"
          - "prism-react-renderer"
      # Development tools
      dev-tools:
        dependency-type: "development"
        patterns:
          - "eslint*"
          - "prettier*"
