FORMAT_VERSION = 2

[STEP1]
INCLUDE = ["486", "488", "489", "490", "491", "492", "493", "494", "495", "496", "497", "498", "499"]
ROLES = [
  { FIX = ["KD"] },
]

[STEP2]
INCLUDE = "ALL"
ROLES_FROM = "STEP1"
ROLES = [
  { FIX = ["KOFF"] },
]
