[experiment]
name       = "dcest_15n"
time_t1    = 0.2
carrier    = 118.0
b1_frq     = 20.0
b1_inh_res = 5
sw         = 700.0
pw90       = 36.0e-6

[conditions]
h_larmor_frq = 800.0
label        = ["2H"]
# p_total      = 1.0e-3
# sample       = "example"
# temperature  = 25.0

[data]
path           = "../Data/700Hz/"
error          = "file"
filter_offsets = [[0.0, 20.0]]
profiles       = [
    ["G2N", "G2N-HN.out"],
    ["H3N", "H3N-HN.out"],
    ["K4N", "K4N-HN.out"],
    ["S5N", "S5N-HN.out"],
    ["L6N", "L6N-HN.out"],
]
