[STEP1]
INCLUDE  = ["L24HD2", "L25HD1", "V30HG1", "V30HG2", "M40HE", "I44HD1"]
PB       = "fix"
KEX_AB   = "fix"

[STEP2]
PB       = "fit"
KEX_AB   = "fit"

[STEP3]
INCLUDE  = "all"
PB       = "fix"
KEX_AB   = "fix"
