name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
        include:
          # Python 3.14 is informational - allow failures while ecosystem catches up
          - python-version: "3.14"
            experimental: true
    continue-on-error: ${{ matrix.experimental || false }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest -q

      - name: Run type checker
        run: uv run ty check
        # Don't fail on type check for experimental Python versions
        continue-on-error: ${{ matrix.experimental || false }}
